#
# Simple _developement_ environment for vantage6.
#
services:
  v6-server:
    # TODO: We could also specify the build instead of pulling from an image.
    #       At the moment, we just assume that V6_VERSION is the latest, so
    #       this "should" be ok enough for development. (Same applies to nodes)
    image: harbor2.vantage6.ai/infrastructure/server:${V6_VERSION}
    depends_on:
      - v6-database
    ports:
      - "127.0.6.1:80:80"
    environment:
      V6_SECRET_KEY_FILE: /run/secrets/v6-secret-key
      V6_INITIAL_ROOT_PASSWORD_FILE: /run/secrets/v6-root-password
      V6_DESCRIPTION: "A description of this server"
      V6_POSTGRES_HOST: v6-database
      V6_POSTGRES_USER: postgres
      V6_POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      V6_POSTGRES_DATABASE: vantage6
    volumes:
      - ./vantage6_docker/v6-server/:/start-up.d/v6-server/
      - ./vantage6_docker/v6-common/:/start-up.d/common/
      # Development only:
      - ./dev-v6-server/:/start-up-hooks.d/
      - ./vantage6/:/vantage6/
    command: ["/start-up.d/v6-server/run.sh"]
    secrets:
      - v6-secret-key
      - v6-root-password
      - postgres-password

  v6-ui:
    image: harbor2.vantage6.ai/infrastructure/ui
    depends_on:
      - v6-server
    ports:
      - "127.0.6.1:8080:80"
    environment:
      SERVER_URL: http://127.0.6.1
      API_PATH: /api

  v6-database:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vantage6
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    secrets:
      - postgres-password

  v6-node-mars:
    image: harbor2.vantage6.ai/infrastructure/node:${V6_VERSION}
    depends_on:
      - v6-server
    environment:
      V6_API_KEY_FILE: /run/secrets/v6-node-mars-api-key
      V6_SERVER_URL: http://v6-server
      V6_SERVER_PORT: 80
      V6_API_PATH: /api
    command: ["/start-up.d/v6-node/run.sh"]
    volumes:
      - ./vantage6_docker/v6-node/:/start-up.d/v6-node/
      - ./vantage6_docker/v6-common/:/start-up.d/common/
      # development only
      # to avoid having to build the docker image, we live mount it (might require restart of container)
      - ./vantage6/:/vantage6/
      # databases and databases.yml. Mounted /mnt because this is hardcoded in v6
      # see: https://github.com/vantage6/vantage6/blob/version/3.10.3/vantage6-node/vantage6/node/docker/docker_manager.py#L202-L205
      - ./dev-nodes-databases/mars/:/mnt/
      # node container needs to talk to docker itself to start containers (algorithms)
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - v6-node-mars-api-key

  v6-node-saturn:
    image: harbor2.vantage6.ai/infrastructure/node:${V6_VERSION}
    depends_on:
      - v6-server
    environment:
      V6_API_KEY_FILE: /run/secrets/v6-node-saturn-api-key
      V6_SERVER_URL: http://v6-server
      V6_SERVER_PORT: 80
      V6_API_PATH: /api
    command: ["/start-up.d/v6-node/run.sh"]
    volumes:
      - ./vantage6_docker/v6-node/:/start-up.d/v6-node/
      - ./vantage6_docker/v6-common/:/start-up.d/common/
      # development only
      - ./vantage6/:/vantage6/
      # databases and databases.yml. Mounted /mnt because this is hardcoded in v6
      # see: https://github.com/vantage6/vantage6/blob/version/3.10.3/vantage6-node/vantage6/node/docker/docker_manager.py#L202-L205
      - ./dev-nodes-databases/saturn/:/mnt/
      # node container needs to talk to docker itself to start containers (algorithms)
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - v6-node-saturn-api-key

  v6-node-jupiter:
    image: harbor2.vantage6.ai/infrastructure/node:${V6_VERSION}
    depends_on:
      - v6-server
    environment:
      V6_API_KEY_FILE: /run/secrets/v6-node-jupiter-api-key
      V6_SERVER_URL: http://v6-server
      V6_SERVER_PORT: 80
      V6_API_PATH: /api
    command: ["/start-up.d/v6-node/run.sh"]
    volumes:
      - ./vantage6_docker/v6-node/:/start-up.d/v6-node/
      - ./vantage6_docker/v6-common/:/start-up.d/common/
      # development only
      - ./vantage6/:/vantage6/
      # databases and databases.yml. Mounted /mnt because this is hardcoded in v6
      # see: https://github.com/vantage6/vantage6/blob/version/3.10.3/vantage6-node/vantage6/node/docker/docker_manager.py#L202-L205
      - ./dev-nodes-databases/jupiter/:/mnt/
      # node container needs to talk to docker itself to start containers (algorithms)
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - v6-node-jupiter-api-key

secrets:
  v6-secret-key:
    file: ./dev-secrets/secret-key
  v6-root-password:
    file: ./dev-secrets/initial-root-password
  postgres-password:
    file: ./dev-secrets/postgres-password
  v6-node-mars-api-key:
    file: ./dev-secrets/node-mars-api-key
  v6-node-saturn-api-key:
    file: ./dev-secrets/node-saturn-api-key
  v6-node-jupiter-api-key:
    file: ./dev-secrets/node-jupiter-api-key
