#
# Simple developement environment for vantage6 [EXPERIMENTAL]
#
services:
  v6-server:
    # TODO: We could also specify the build instead of pulling from an image.
    #       At the moment, we just assume that V6_VERSION is the latest, so
    #       this "should" be ok enough for development. (Same applies to nodes).
    #       Using the image could become a problem if there are changs outside
    #       /vantage6 in the image that are required for changes in /vantage6
    #       (package dependencies for example).
    image: harbor2.vantage6.ai/infrastructure/server:${V6_VERSION}
    depends_on:
      - v6-database
    ports:
      # TODO: This work on Linux, but I'm not sure it works on Docker Desktop?
      - "127.0.6.1:80:80"
      - "127.0.6.1:5678:5678"
    environment:
      ENV_V6_SECRET_KEY_FILE: /run/secrets/v6-secret-key
      V6_INITIAL_ROOT_PASSWORD_FILE: /run/secrets/v6-root-password
      ENV_V6_DESCRIPTION: "Development vantage6 server."
      ENV_V6_POSTGRES_HOST: v6-database
      ENV_V6_POSTGRES_USER: postgres
      ENV_V6_POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      ENV_V6_POSTGRES_DATABASE: vantage6
      # For development only, as we live mount /vantage6 we don't want
      # root:root .pyc files on the host.
      PYTHONDONTWRITEBYTECODE: 1
      GEVENT_SUPPORT: "True"
    volumes:
      - ./vantage6_docker/v6-server/:/start-up.d/app/
      - ./vantage6_docker/v6-common/:/start-up.d/common/
      # Development only:
      - ./dev-v6-server/:/start-up.d/custom.d/
      - ./vantage6/:/vantage6/
    command: ["/start-up.d/app/run.sh"]
    secrets:
      - v6-secret-key
      - v6-root-password
      - postgres-password

  v6-ui:
    image: harbor2.vantage6.ai/infrastructure/ui
    depends_on:
      - v6-server
    ports:
      - "127.0.6.1:8080:80"
    environment:
      SERVER_URL: http://127.0.6.1
      API_PATH: /api

  v6-database:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vantage6
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    secrets:
      - postgres-password

  v6-node-mars:
    image: harbor2.vantage6.ai/infrastructure/node:${V6_VERSION}
    depends_on:
      - v6-server
    ports:
      - "127.0.6.10:5678:5678"
    environment:
      ENV_V6_API_KEY_FILE: /run/secrets/v6-node-mars-api-key
      ENV_V6_SERVER_URL: http://v6-server
      ENV_V6_SERVER_PORT: 80
      ENV_V6_API_PATH: /api
      DATA_VOLUME_NAME: mars-data
      # For development only, as we live mount /vantage6 we don't want
      # root:root .pyc files on the host.
      PYTHONDONTWRITEBYTECODE: 1
      GEVENT_SUPPORT: "True"
    command: ["/start-up.d/app/run.sh"]
    volumes:
      - ./vantage6_docker/v6-node/:/start-up.d/app/
      - ./vantage6_docker/v6-common/:/start-up.d/common/
      # node container needs to talk to docker itself to start containers (algorithms)
      - /var/run/docker.sock:/var/run/docker.sock
      # same data volume will be mounted on the algorithm container
      - mars-data:/mnt/data
      # databases and databases.yaml.j2. Mounted /mnt because this is hardcoded in v6
      # see: https://github.com/vantage6/vantage6/blob/version/3.10.3/vantage6-node/vantage6/node/docker/docker_manager.py#L202-L205
      - ./dev-nodes-databases/mars/:/mnt/databases
      # development only
      - ./vantage6/:/vantage6/
      # includes pre_run.sh, that creates fixtures and allows for debugging (via debugpy)
      - ./dev-v6-nodes/:/start-up.d/custom.d/
    secrets:
      - v6-node-mars-api-key

  v6-node-saturn:
    image: harbor2.vantage6.ai/infrastructure/node:${V6_VERSION}
    depends_on:
      - v6-server
    ports:
      - "127.0.6.11:5678:5678"
    environment:
      ENV_V6_API_KEY_FILE: /run/secrets/v6-node-saturn-api-key
      ENV_V6_SERVER_URL: http://v6-server
      ENV_V6_SERVER_PORT: 80
      ENV_V6_API_PATH: /api
      DATA_VOLUME_NAME: saturn-data
      # For development only, as we live mount /vantage6 we don't want
      # root:root pyc's on the host.
      PYTHONDONTWRITEBYTECODE: 1
      GEVENT_SUPPORT: "True"
    command: ["/start-up.d/app/run.sh"]
    volumes:
      - ./vantage6_docker/v6-node/:/start-up.d/app/
      - ./vantage6_docker/v6-common/:/start-up.d/common/
      # node container needs to talk to docker itself to start containers (algorithms)
      - /var/run/docker.sock:/var/run/docker.sock
      # same data volume will be mounted on the algorithm container
      - saturn-data:/mnt/data
      # databases and databases.yaml.j2. Mounted /mnt because this is hardcoded in v6
      # see: https://github.com/vantage6/vantage6/blob/version/3.10.3/vantage6-node/vantage6/node/docker/docker_manager.py#L202-L205
      - ./dev-nodes-databases/saturn/:/mnt/databases
      # development only
      - ./vantage6/:/vantage6/
      # includes pre_run.sh, that creates fixtures and allows for debugging (via debugpy)
      - ./dev-v6-nodes/:/start-up.d/custom.d/
    secrets:
      - v6-node-saturn-api-key

  v6-node-jupiter:
    image: harbor2.vantage6.ai/infrastructure/node:${V6_VERSION}
    depends_on:
      - v6-server
    environment:
      ENV_V6_API_KEY_FILE: /run/secrets/v6-node-jupiter-api-key
      ENV_V6_SERVER_URL: http://v6-server
      ENV_V6_SERVER_PORT: 80
      ENV_V6_API_PATH: /api
      DATA_VOLUME_NAME: jupiter-data
      # For development only, as we live mount /vantage6 we don't want
      # root:root pyc's on the host.
      PYTHONDONTWRITEBYTECODE: 1
      GEVENT_SUPPORT: "True"
    command: ["/start-up.d/app/run.sh"]
    volumes:
      - ./vantage6_docker/v6-node/:/start-up.d/app/
      - ./vantage6_docker/v6-common/:/start-up.d/common/
      # node container needs to talk to docker itself to start containers (algorithms)
      - /var/run/docker.sock:/var/run/docker.sock
      # same data volume will be mounted on the algorithm container
      - jupiter-data:/mnt/data
      # databases and databases.yaml.j2. Mounted /mnt because this is hardcoded in v6
      # see: https://github.com/vantage6/vantage6/blob/version/3.10.3/vantage6-node/vantage6/node/docker/docker_manager.py#L202-L205
      - ./dev-nodes-databases/jupiter/:/mnt/databases
      # development only
      - ./vantage6/:/vantage6/
      # includes pre_run.sh, that creates fixtures and allows for debugging (via debugpy)
      - ./dev-v6-nodes/:/start-up.d/custom.d/
    secrets:
      - v6-node-jupiter-api-key

# NOTE: nodes will copy file databases to this volume (/mnt/data), and mount it
#       in the algorithm container. They will also create task directories. (WIP)
#       Vantage6 uses the env var DATA_VOLUME_NAME to determine the name of the
#       volume to mount in the algorithm container.
volumes:
  mars-data:
    name: "mars-data"
  saturn-data:
    name: "saturn-data"
  jupiter-data:
    name: "jupiter-data"

secrets:
  v6-secret-key:
    file: ./dev-secrets/secret-key
  v6-root-password:
    file: ./dev-secrets/initial-root-password
  postgres-password:
    file: ./dev-secrets/postgres-password
  v6-node-mars-api-key:
    file: ./dev-secrets/node-mars-api-key
  v6-node-saturn-api-key:
    file: ./dev-secrets/node-saturn-api-key
  v6-node-jupiter-api-key:
    file: ./dev-secrets/node-jupiter-api-key
